import { Platform, StyleSheet } from "react-native";
import { COLORS } from "./color";

export const SPACING = {
  xs: 6,
  sm: 10,
  md: 14,
  lg: 20,
  xl: 28,
} as const;

export const RADIUS = {
  sm: 8,
  md: 12,
  lg: 16,
} as const;

export const TYPO = StyleSheet.create({
  h1: { color: COLORS.backgroundn, fontSize: 32, fontWeight: "700" },
  h2: { color: COLORS.backgroundn, fontSize: 22, fontWeight: "700" },
  body: { color: COLORS.backgroundn, fontSize: 16 },
  muted: { color: COLORS.quaternary, fontSize: 14 },
  link: { color: COLORS.quinary, fontWeight: "600" },
});

export const LAYOUT = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.backgroundd, padding: SPACING.lg },
  center: { alignItems: "center", justifyContent: "center" },
  rowCenter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  gapSm: { rowGap: SPACING.sm, columnGap: SPACING.sm },
  gapMd: { rowGap: SPACING.md, columnGap: SPACING.md },
  container: {
    flex: 1,
    paddingHorizontal: SPACING.lg,
    backgroundColor: COLORS.backgroundd,
  },
  surface: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: RADIUS.md,
  },
  surfaceAlt: {
    backgroundColor: COLORS.surfaceAlt,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: RADIUS.md,
  },
});

export const FORMS = StyleSheet.create({
  label: {
    color: COLORS.backgroundn,
    marginTop: SPACING.sm,
    marginBottom: SPACING.xs,
  },
  input: {
    color: COLORS.backgroundn,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
  },
  placeholder: { color: COLORS.muted },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.md,
    height: 50,
  },
  inputText: { flex: 1, color: COLORS.text, fontSize: 14 },
  segmentedWrap: {
    flexDirection: "row",
    gap: SPACING.sm,
    backgroundColor: COLORS.surfaceAlt,
    padding: SPACING.sm,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  segmentedItem: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.quaternary,
  },
  segmentedItemActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  checkboxRow: { flexDirection: "row", alignItems: "center", gap: SPACING.sm },
});

export const BUTTONS = StyleSheet.create({
  primary: {
    backgroundColor: COLORS.primary,
    padding: SPACING.md + 2,
    borderRadius: RADIUS.lg,
    alignItems: "center",
  },
  primaryText: { color: COLORS.backgroundn, fontWeight: "700" },
  secondary: {
    backgroundColor: "transparent",
    padding: SPACING.md + 2,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
  },
  secondaryText: { color: COLORS.backgroundn, fontWeight: "600" },
  ghost: {
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.quaternary,
    alignItems: "center",
  },
  ghostText: { color: COLORS.backgroundn, fontWeight: "600" },
  publish: {
    marginTop: SPACING.lg,
    marginBottom: SPACING.md,
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.lg,
    paddingVertical: SPACING.lg,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  publishText: { color: "#fff", fontWeight: "900" },
});

export const signOut = StyleSheet.create({
  signOut: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.backgroundd,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 18,
    borderWidth: 1,
    borderColor: COLORS.quaternary,
  },
  signOutText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: "700",
    marginLeft: 8,
  },
});

export const HEADER = StyleSheet.create({
  topSpace: { paddingTop: 6, paddingHorizontal: 16, paddingBottom: 8 },
  title: { color: COLORS.heading, fontSize: 18, fontWeight: "800" },
  subtitle: { color: COLORS.muted, fontSize: 12, marginTop: 2 },
});

export const UPLOAD = StyleSheet.create({
  box: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingVertical: 22,
    paddingHorizontal: 14,
    alignItems: "center",
    backgroundColor: COLORS.surfaceAlt,
  },
  text: { color: COLORS.muted, marginTop: 8 },
  hint: { color: COLORS.muted, fontSize: 12, marginTop: 2 },
  previewImg: { width: "100%", height: 180 },
  previewActions: {
    position: "absolute",
    right: 10,
    bottom: 10,
    flexDirection: "row",
    columnGap: 8,
  },
  previewBtn: {
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    columnGap: 6,
    borderWidth: 1,
    borderColor: "#000",
  },
  previewBtnText: { color: COLORS.text, fontWeight: "700", fontSize: 12 },
});

export const BOTTOM_BAR = StyleSheet.create({
  bar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 64,
    backgroundColor: COLORS.surfaceAlt,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  item: { alignItems: "center", rowGap: 4 },
  text: { color: COLORS.text, fontSize: 12 },
});

export const MODAL = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  card: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -160 }, { translateY: -180 }],
    width: 320,
    backgroundColor: COLORS.surfaceAlt,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    padding: 14,
  },
  title: {
    color: COLORS.heading,
    fontWeight: "800",
    fontSize: 16,
    marginBottom: 6,
  },
  actions: {
    marginTop: 8,
    flexDirection: "row",
    justifyContent: "flex-end",
    columnGap: 10,
  },
  btnGhost: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10 },
  btnGhostText: { color: COLORS.muted, fontWeight: "700" },
  btnPrimary: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
  },
  btnPrimaryText: { color: "#0B1416", fontWeight: "900" },
});

export const MAP = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.backgroundd },
  map: { flex: 1 },
  searchWrap: {
    position: "absolute",
    top: 14,
    left: 12,
    right: 12,
    zIndex: 10,
  },
  chipRow: {
    position: "absolute",
    bottom: 18,
    left: 12,
    right: 12,
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  chip: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: COLORS.quinary,
  },
  chipText: { fontWeight: "600", color: COLORS.primary },
  calloutTitle: { fontWeight: "700", marginBottom: 4 },
  markerPin: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: COLORS.secondary,
    borderColor: COLORS.backgroundd,
    borderWidth: 2,
  },
  stepper: {
    position: "absolute",
    top: 8,
    left: 0,
    right: 0,
    zIndex: 20,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    paddingVertical: 6,
    backgroundColor: "rgba(255,255,255,0.95)",
  },
  step: { color: "#7d8b8c", fontWeight: "700" },
  stepActive: { color: COLORS.primary },
  chipsRow: {
    position: "absolute",
    top: 86,
    left: 16,
    right: 16,
    zIndex: 12,
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  chipTitle: { color: "#7c8a8c", fontSize: 12, marginBottom: 2 },
  chipValue: { fontWeight: "800", fontSize: 16 },
  bottomCard: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingTop: 14,
    paddingBottom: 24,
    borderTopLeftRadius: RADIUS.lg,
    borderTopRightRadius: RADIUS.lg,
    backgroundColor: COLORS.backgroundn,
    alignItems: "center",
    gap: 8,
  },
  bottomTitle: { color: "#7c8a8c", fontSize: 14 },
  bottomEta: { fontSize: 18, fontWeight: "800" },
  placeName: { fontSize: 16, fontWeight: "700" },
  primaryBtn: {
    marginTop: 8,
    backgroundColor: COLORS.backgroundd,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: RADIUS.md,
  },
  primaryBtnText: { color: COLORS.backgroundn, fontWeight: "700" },
});
export const CreateEventStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.backgroundd },
  topSpace: { paddingTop: 6, paddingHorizontal: 16, paddingBottom: 8 },
  headerTitle: { color: COLORS.heading, fontSize: 18, fontWeight: "800" },
  headerSub: { color: COLORS.muted, fontSize: 12, marginTop: 2 },

  uploadBox: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingVertical: 22,
    paddingHorizontal: 14,
    alignItems: "center",
    backgroundColor: COLORS.surfaceAlt,
  },
  uploadText: { color: COLORS.muted, marginTop: 8 },
  uploadHint: { color: COLORS.muted, fontSize: 12, marginTop: 2 },
  previewImg: { width: "100%", height: 180, resizeMode: "cover" },
  previewActions: {
    position: "absolute",
    right: 10,
    bottom: 10,
    flexDirection: "row",
    gap: 8,
  },
  previewBtn: {
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#000",
  },
  previewBtnText: { color: COLORS.text, fontWeight: "700", fontSize: 12 },

  form: { paddingHorizontal: 16 },
  label: {
    color: COLORS.text,
    fontWeight: "800",
    marginBottom: 6,
    marginTop: 12,
  },
  inputWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    backgroundColor: COLORS.surface,
    paddingHorizontal: 12,
    height: 50,
  },
  input: { flex: 1, color: COLORS.text, fontSize: 14 },
  inputText: { flex: 1, fontSize: 14 },

  row: { flexDirection: "row", marginTop: 2 },

  publishBtn: {
    marginHorizontal: 16,
    marginTop: 22,
    marginBottom: 16,
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  publishText: { color: "#fff", fontWeight: "900", fontSize: 15 },

  // Modals
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  modalCard: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -200 }, { translateY: -180 }],
    width: 320,
    backgroundColor: COLORS.surfaceAlt,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    padding: 14,
  },
  modalTitle: {
    color: COLORS.heading,
    fontWeight: "800",
    fontSize: 16,
    marginBottom: 6,
  },
  modalActions: {
    marginTop: 8,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  btnGhost: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 10 },
  btnGhostText: { color: COLORS.muted, fontWeight: "700" },
  btnPrimary: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
  },
  btnPrimaryText: { color: "#0B1416", fontWeight: "900" },
});
// Styles used by components/UserMore.tsx
export const moreStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.backgroundd,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  headerTitle: {
    color: COLORS.primary,
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 14,
  },
  profileCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.backgroundd,
    padding: 16,
    borderRadius: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.quaternary,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    marginRight: 12,
  },
  company: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: "700",
  },
  role: {
    color: COLORS.secondary,
    fontSize: 13,
    marginTop: 2,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
  },
  rating: {
    color: COLORS.primary,
    marginLeft: 6,
    fontWeight: "600",
  },
  item: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.backgroundd,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.quaternary,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
      },
      android: { elevation: 2 },
    }),
  },
  leftIcon: {
    width: 28,
    alignItems: "center",
    marginRight: 10,
  },
  itemText: {
    color: COLORS.primary,
    fontSize: 16,
    flex: 1,
    fontWeight: "600",
  },
  value: {
    color: COLORS.secondary,
    fontSize: 14,
    marginRight: 6,
  },
});
